### ISSUE TITLE
GAN implementation

### ISSUE THREAD

**Issue by mbalatsko** [BiDAlab/BeCAPTCHA-Mouse#1]
Hello,

I found your research paper very interesting and informative, but I haven't found in paper one thing that I will be glad to reproduce - technical details of GAN model construction and training. It would be very helpful for me if you could provide more information about it or maybe you have some sample code that could be reused?

Thanks,
Maksym Balatsko

**Comment by tha23rd** [comment]
Hi, any follow up on this from the publishers of the paper? I too would be interested to learn more specifics about the GAN model used to produce the synthetic mouse data.

**Comment by BiDAlab** [comment]
Dear Maksym,

thanks for your interest, we are working on a new version of the paper with improved explanation and extended experimentation.  We hope to release it soon.

Best,
Aythami Morales.

**Comment by tha23rd** [comment]
> 
> 
> Dear Maksym,
> 
> thanks for your interest, we are working on a new version of the paper with improved explanation and extended experimentation. We hope to release it soon.
> 
> Best,
> Aythami Morales.

Hi, any update on this?

**Comment by BiDAlab** [comment]
Dear tha23rd,

we have released a new version of the paper including new experiments and improved explanation. You can read the new version here: https://arxiv.org/pdf/2005.00890.pdf

Best,
Aythami.

**Comment by romanholidaypancakes** [comment]
@BiDAlab  hi, can you provide the code and algorithm reference of the example
